// <auto-generated />
namespace ProjetoEF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class EntityF06 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EntityF06));
        
        string IMigrationMetadata.Id
        {
            get { return "202301202123563_EntityF06"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
